version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: stackfood-payments-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,sns,sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./localstack-data:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - stackfood-network

  payments-api:
    build:
      context: .
      dockerfile: src/StackFood.Payments.API/StackFood.Payments.API/Dockerfile
    container_name: stackfood-payments-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - AWS__Region=us-east-1
      - AWS__ServiceURL=http://localstack:4566
      - AWS__SnsTopicArn=arn:aws:sns:us-east-1:000000000000:sns-payment-events
      - DynamoDB__TableName=Payments
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    depends_on:
      - localstack
    networks:
      - stackfood-network
    restart: unless-stopped

networks:
  stackfood-network:
    driver: bridge
