apiVersion: v1
kind: ConfigMap
metadata:
  name: stackfood-payments-config
  labels:
    app.kubernetes.io/name: stackfood-payments
    app.kubernetes.io/part-of: stackfood
data:
  # AWS DynamoDB Configuration
  AWS__Region: "us-east-1"
  AWS__ServiceURL: ""
  DYNAMODB_TABLE_NAME: "stackfood-payments"

  # AWS SNS Configuration
  AWS__SNS__PaymentEventsTopicArn: "arn:aws:sns:us-east-1:975050205506:stackfood-sns-payments-topic"

  # AWS SQS Configuration
  AWS__SQS__QueueUrl: "https://sqs.us-east-1.amazonaws.com/975050205506/stackfood-sqs-payments-queue"

  # Application Settings
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8082"
