apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: payments

bases:
  - ../base

resources:
  - configmap.yaml
  - secret.yaml

images:
  - name: ghcr.io/stack-food/stackfood-payments-api
    newTag: main

replicas:
  - name: stackfood-payments
    count: 2
