apiVersion: v1
kind: Secret
metadata:
  name: stackfood-payments-secrets
  labels:
    app.kubernetes.io/name: stackfood-payments
    app.kubernetes.io/part-of: stackfood
type: Opaque
stringData:
  # AWS Credentials (if not using IRSA)
  AWS_ACCESS_KEY_ID: "REPLACE_WITH_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "REPLACE_WITH_SECRET_ACCESS_KEY"
  AWS_SESSION_TOKEN: "REPLACE_WITH_SESSION_TOKEN"